export const states = {
  init: "is-init",
  active: "is-active",
  done: 'is-done',
  fixed: "is-fixed",
  scrolling: "is-scrolling",
  hover: "is-hover",
  searching: "is-searching",
  changed: "is-changed",
  focus: "is-focus",
  open: "is-open",
  close: "is-close",
  filled: "is-filled",
  unfolded: "is-unfolded",
  disabled: "is-disabled",
  highlight: "is-highlight",
  select: "is-selected",
  flip: "is-flip",
  error: "is-error",
  warning: "is-warning",
  valid: "is-valid",
  animate: "is-animate",
  success: "is-success",
  empty: "is-empty",
  applied: "is-applied",
  expired: "is-expired",
};
